# sources.yaml
version: 2

sources:
  - name: rds
    database: northwinds_rds
    schema: pagila_mart_public
    freshness: 
        warn_after: {count: 24, period: hour}
        error_after: {count: 36, period: hour}
        filter: datedif('day', _fivetran_synced, current_timestamp) < 2
    loaded_at_field: _fivetran_synced

    tables:
      - name: dimcustomer
        freshness: 
        warn_after: {count: 24, period: hour}
        error_after: {count: 36, period: hour}
        filter: datedif('day', _fivetran_synced, current_timestamp) < 2


